### ISSUE TITLE
后台新增管理员问题

### ISSUE THREAD

**Issue by xmwin** [NeuCharFramework/NCF#107]
后台添加新管理员账号“未赋角色”权限，直接用新管理员账号在后台登录出现找不到页面（404），
![NCF01](https://user-images.githubusercontent.com/7477956/161362040-3065bc5c-ec51-42eb-bee6-5e8aa4ff7aef.png)
然后直接在地址栏输入“https://localhost:44311/Admin/”打开，却可以打开后台默认首页
![NCF02](https://user-images.githubusercontent.com/7477956/161362072-ebcdad3d-4a5f-4875-99b0-881ade1a565c.jpeg)
首页的下面“功能模块”部分又显示了已安装的模块，然后点击“模块”下方的详细页面“按钮”也可以打开模块的详细页面
![NCF03](https://user-images.githubusercontent.com/7477956/161362154-b34d204e-226e-4909-9c0b-80534f418cf7.jpeg)
没有相应“角色”权限的空账号又可以操作模块详细页面上的两个“功能”按钮哦
应该是页面权限没有配置到，之前有跟苏总提过，好像没有更新到，
空“角色”账号登录后在地址栏直接输入后台其他页面地址打开，都是出现找不到页面(404)，没有其他提示，不知道是不是“故意”的，呵呵

**Comment by JeffreySu** [comment]
是的这个问题时没有给菜单的权限，我们后续版本会更新。接下去我们会上前后端分离的版本。
