### ISSUE TITLE
Xncf 模块管理和导航问题

### ISSUE THREAD

**Issue by zfchai** [NeuCharFramework/NCF#118]
- Xncf 模块新增后，进入【模块管理】页面，点击【进入首页】，页面无法访问。

比如：Senparc.Xncf.Swagger 模块，页面操作如下：

![1](https://user-images.githubusercontent.com/82487746/205013124-70774894-894f-4728-99d5-37309374a76f.jpg)

![2](https://user-images.githubusercontent.com/82487746/205013156-f03e7188-a3bd-4868-849a-3471e425e166.jpg)

- Xncf 模块状态关闭时，页面中无法操作（符合预期），但实际的访问地址在浏览器中依然能访问。

![3](https://user-images.githubusercontent.com/82487746/205013174-617f12eb-5ffe-4f88-9d96-f387503992ac.jpg)

**Comment by JeffreySu** [comment]
1、这个地址配置是有问题的，你在根目录下面打开Swagger即可。
2、对的，这里关闭状态下是不允许操作，但故意没有阻止对应系统页面的运行（实际开发过程中你可以根据判断来阻止，判断方式你可以关注一下首页顶部 Swagger 的显示和关闭）。
