### ISSUE TITLE
developer 分支update-database 报错

### ISSUE THREAD

**Issue by Yinqingwen** [NeuCharFramework/NCF#16]
最新版developer分支，手动更新数据库，报如下错误：More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands.
我记得数据库连接字符串在Senparc.Web项目里啊

**Comment by JeffreySu** [comment]
需要将 Senparc.Service 项目设为启动项目。然后执行：

```
PM> update-database -Context SenparcEntities
```
