### ISSUE TITLE
源码在调试模式报错

### ISSUE THREAD

**Issue by laoyangcoder** [NeuCharFramework/NCF#60]
我将源代码克隆到本地后，直接调试（按F5）运行。报如下错误：
![QQ图片20210327183718](https://user-images.githubusercontent.com/61358205/112718074-9c163980-8f2b-11eb-8f7e-87dc3da06f75.png)

当我使用非调试模式（ctrl+f5）一切正常。

烦请指导，谢谢！

**Comment by JeffreySu** [comment]
@laoyangcoder  如果你是调试状态下发生这个问题，是正常的，说明系统检测到没有安装的异常，转而会进入安装流程。见 #61
