### ISSUE TITLE
安装过后重新拉取代码 启动报错

### ISSUE THREAD

**Issue by yongyaoli** [NeuCharFramework/NCF#61]
拉取代码后 启动时 OnModelCreating（）中的base.OnModelCreating(modelBuilder);（58行）报错：
"内部异常 NcfUninstallException: TriedMatching 为false,推测系统未进行安装"。
经删除数据库后 重启启动可以正常启动。

**Comment by JeffreySu** [comment]
@yongyaoli 如果你是调试状态下发生这个问题，是正常的，说明系统检测到没有安装的异常，转而会进入安装流程。
