### ISSUE TITLE
使用Mysql CodeFirst 建立数据表主键没有自增，引发数据初始化，

### ISSUE THREAD

**Issue by liwendiao123** [NeuCharFramework/NCF#67]
![image](https://user-images.githubusercontent.com/28423732/121050736-6a530600-c7eb-11eb-94ec-7cf2b3eb1113.png)
是否可以考虑主键INT类型中引入[DatabaseGenerated(DatabaseGeneratedOption.Identity)]

**Comment by JeffreySu** [comment]
@liwendiao123 有具体的错误信息吗？这个问题和Pomelo作者沟通过，目前默认应该是自增的（至少按照目前最新的代码）。

有一个库依赖的问题需要等待Pomelo那边解决。
