### ISSUE TITLE
希望可以支持postgre数据库

### ISSUE THREAD

**Issue by shunpeng** [NeuCharFramework/NCF#85]
可以操作切换数据库最好，有的大项目分很多数据库可以传数据库名字切换最佳

**Comment by JeffreySu** [comment]
已在计划中。

自动安装数据库这个想法不错。

**Comment by JeffreySu** [comment]
@shunpeng 已经发布支持 PostgreSQL 的新版本。

自动安装看了一下似乎没有必要，独立安装包已经足够简单了，后期会考虑直接使用容器镜像自动加载到容器，达到自动安装的目的。
