### ISSUE TITLE
微信Sample生成器页面功能缺失

### ISSUE THREAD

**Issue by Jiangdaoyin** [NeuCharFramework/NCF#86]
您好，我这边按照操作步骤运行了NeuCharFramework项目，在微信Sample生成器页面好像没有运行按钮
![image](https://user-images.githubusercontent.com/40382421/139455312-ffc91efe-9d27-4f85-a0d4-6e8d2f4cbb21.png)

**Comment by JeffreySu** [comment]
@Jiangdaoyin 中途有一个版本确实有这个问题，麻烦你用最新的版本试一下。
